name: Notion → Markdown sync

on:
  schedule:
    - cron: '0 0 * * *'   # daily at 00:00 UTC (change if you want)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  export-notion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clean old exports (optional)
        run: |
          # remove previous exported files if you want deterministic output:
          rm -rf notion-export || true

      - name: Export Notion workspace to Markdown
        # Exports any pages your integration can access into the current working dir.
        uses: Gabriella439/notion-to-markdown@main
        with:
          notion-token: ${{ secrets.NOTION_TOKEN }}

      - name: Show changed files (debug)
        run: git status --porcelain || true

      - name: Commit exported files back to repo
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'                       # add everything changed (the action exports files into the workspace)
          message: 'chore: sync Notion → Markdown'
          author_name: 'notion-sync-bot'
          author_email: 'actions@users.noreply.github.com'
          default_author: github_actions
